CREATE TABLE EXPENSE (
    EXPENSE_ID VARCHAR2(36) PRIMARY KEY,
    USER_ID VARCHAR2(36),
    AMOUNT INTEGER NOT NULL,
    DESCRIPTION VARCHAR(128),
    EXPENSE_DATE DATE NOT NULL,
    STATUS VARCHAR(64) NOT NULL
);
